### PR TITLE
make sure that all packets in the send queue are sent before closing

### LINKED ISSUE #2347: flaky 0.5-RTT data integration test
```early data with QUIC version TLS dev version (WIP) 

  sends 0.5-RTT data

  /home/travis/gopath/src/github.com/lucas-clemente/quic-go/integrationtests/self/early_data_test.go:24

• Failure [1.168 seconds]

early data

/home/travis/gopath/src/github.com/lucas-clemente/quic-go/integrationtests/self/early_data_test.go:18

  with QUIC version TLS dev version (WIP)

  /home/travis/gopath/src/github.com/lucas-clemente/quic-go/integrationtests/self/early_data_test.go:23

    sends 0.5-RTT data [It]

    /home/travis/gopath/src/github.com/lucas-clemente/quic-go/integrationtests/self/early_data_test.go:24

    Timed out after 1.000s.

    Expected

        <chan struct {} | len:0, cap:0>: 0xc006839980

    to be closed

    /home/travis/gopath/src/github.com/lucas-clemente/quic-go/integrationtests/self/early_data_test.go:68

    Full Stack Trace

    github.com/lucas-clemente/quic-go/integrationtests/self_test.glob..func5.1.1()

    	/home/travis/gopath/src/github.com/lucas-clemente/quic-go/integrationtests/self/early_data_test.go:68 +0xb94

    github.com/onsi/ginkgo/internal/leafnodes.(*runner).runSync(0xc0000abda0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)

    	/home/travis/gopath/pkg/mod/github.com/onsi/ginkgo@v1.12.0/internal/leafnodes/runner.go:113 +0xb8

    github.com/onsi/ginkgo/internal/leafnodes.(*runner).run(0xc0000abda0, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)

    	/home/travis/gopath/pkg/mod/github.com/onsi/ginkgo@v1.12.0/internal/leafnodes/runner.go:64 +0xcf

    github.com/onsi/ginkgo/internal/leafnodes.(*ItNode).Run(0xc0000b6c20, 0xbea0c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)

    	/home/travis/gopath/pkg/mod/github.com/onsi/ginkgo@v1.12.0/internal/leafnodes/it_node.go:26 +0x64

    github.com/onsi/ginkgo/internal/spec.(*Spec).runSample(0xc00020fef0, 0x0, 0xbea0c0, 0xc000084900)

    	/home/travis/gopath/pkg/mod/github.com/onsi/ginkgo@v1.12.0/internal/spec/spec.go:215 +0x5b5

    github.com/onsi/ginkgo/internal/spec.(*Spec).Run(0xc00020fef0, 0xbea0c0, 0xc000084900)

    	/home/travis/gopath/pkg/mod/github.com/onsi/ginkgo@v1.12.0/internal/spec/spec.go:138 +0x101

    github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpec(0xc00017de00, 0xc00020fef0, 0x0)

    	/home/travis/gopath/pkg/mod/github.com/onsi/ginkgo@v1.12.0/internal/specrunner/spec_runner.go:200 +0x10f

    github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpecs(0xc00017de00, 0x1)

    	/home/travis/gopath/pkg/mod/github.com/onsi/ginkgo@v1.12.0/internal/specrunner/spec_runner.go:170 +0x120

    github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).Run(0xc00017de00, 0xc00002adc0)

    	/home/travis/gopath/pkg/mod/github.com/onsi/ginkgo@v1.12.0/internal/specrunner/spec_runner.go:66 +0x117

    github.com/onsi/ginkgo/internal/suite.(*Suite).Run(0xc0000d0230, 0x7fbc82c3c5c8, 0xc0001bb800, 0xb13e46, 0x16, 0xc00003f300, 0x1, 0x1, 0xbf8b20, 0xc000084900, ...)

    	/home/travis/gopath/pkg/mod/github.com/onsi/ginkgo@v1.12.0/internal/suite/suite.go:62 +0x42b

    github.com/onsi/ginkgo.RunSpecsWithCustomReporters(0xbea820, 0xc0001bb800, 0xb13e46, 0x16, 0xc00004f718, 0x1, 0x1, 0x40e628)

    	/home/travis/gopath/pkg/mod/github.com/onsi/ginkgo@v1.12.0/ginkgo_dsl.go:226 +0x217

    github.com/onsi/ginkgo.RunSpecs(0xbea820, 0xc0001bb800, 0xb13e46, 0x16, 0x171775dffc)

    	/home/travis/gopath/pkg/mod/github.com/onsi/ginkgo@v1.12.0/ginkgo_dsl.go:207 +0x16e

    github.com/lucas-clemente/quic-go/integrationtests/self_test.TestSelf(0xc0001bb800)

    	/home/travis/gopath/src/github.com/lucas-clemente/quic-go/integrationtests/self/self_suite_test.go:127 +0x96

    testing.tRunner(0xc0001bb800, 0xb35438)

    	/home/travis/.gimme/versions/go1.13.7.linux.amd64/src/testing/testing.go:909 +0xc9

    created by testing.(*T).Run

    	/home/travis/.gimme/versions/go1.13.7.linux.amd64/src/testing/testing.go:960 +0x350

### PR DESCRIPTION
**Pull request by marten-seemann**
Fixes #2347.

### CODE REVIEW

File: send_queue.go [hunk 1]
```diff
@@ -2,13 +2,15 @@ package quic
 
 type sendQueue struct {
 	queue     chan *packedPacket
-	closeChan chan struct{}
+	closeChan chan struct{} // closed when Close() is called
+	closed    chan struct{} // closed when the run loop returns
```
Comment (lucas-clemente) [inline send_queue.go]: Nit: Maybe make the naming a bit more clear? E.g. `closeCalled` and `runStopped`?

**Comment by marten-seemann** [comment]
There's only a single close path for the `sendQueue`. If an error occurs when writing the the UDP conn, `Run()` returns immediately.

File: send_queue.go (hunk 1 above)
Comment (marten-seemann) [reply send_queue.go]: Done.
