### PR TITLE
fix flaky TestDrainServerAcceptQueue

### LINKED ISSUE #5192: flaky TestDrainServerAcceptQueue
```
 === RUN   TestDrainServerAcceptQueue
    close_test.go:111: 
        	Error Trace:	/Users/runner/work/quic-go/quic-go/integrationtests/self/close_test.go:111
        	Error:      	Received unexpected error:
        	            	context canceled
        	Test:       	TestDrainServerAcceptQueue
        	Messages:   	server connection closed
--- FAIL: TestDrainServerAcceptQueue (0.14s)

### PR DESCRIPTION
**Pull request by marten-seemann**
The connections are not necessarily accepted in the same order that they are dialed.

### CODE REVIEW

File: integrationtests/self/close_test.go [hunk 1]
```diff
@@ -107,9 +107,8 @@ func TestDrainServerAcceptQueue(t *testing.T) {
 		c, err := server.Accept(ctx)
 		require.NoError(t, err)
 		// make sure the connection is not closed
-		require.NoError(t, conns[i].Context().Err(), "client connection closed")
-		require.NoError(t, c.Context().Err(), "server connection closed")
-		conns[i].CloseWithError(0, "")
+		require.NoError(t, context.Cause(conns[i].Context()), "client connection closed")
+		require.NoError(t, context.Cause(c.Context()), "server connection closed")
```
Comment (marten-seemann) [inline integrationtests/self/close_test.go:111]: This will make the error message more helpful.
