### PR TITLE
fix INVALID_STREAM error when a retransmission for a server-side stream arrives after the stream is closed

### LINKED ISSUE #691: Stream ID sequencing issue
I'm seeing errors like:

 - InvalidStreamID: attempted to open stream 4 from client-side

I've read the QUIC docs but am still left with the questions:

 - Are we able to arbitrarily open streams on the client and server, or does it have to be Client, Server, Client, alternating?
 - If we are able to open streams in any order, then why is this error in place?

Thanks!

### PR DESCRIPTION
**Pull request by marten-seemann**
Fixes #691.

### CODE REVIEW

File: streams_map.go [hunk 1]
```diff
@@ -83,15 +83,27 @@ func (m *streamsMap) GetOrOpenStream(id protocol.StreamID) (*stream, error) {
...
+	if m.perspective == protocol.PerspectiveClient {
+		if id%2 == 1 {
+			if id <= m.nextStream { // this is a client-side stream that we already opened.
+				return nil, nil
+			}
+			return nil, qerr.Error(qerr.InvalidStreamID, fmt.Sprintf("attempted to open stream %d from server-side", id))
+		}
+		if id <= m.highestStreamOpenedByPeer { // this is a server-side stream that doesn't exist anymore. Must have been closed already
+			return nil, nil
+		}
```
Comment (lucas-clemente) [inline streams_map.go]: I'm fine with merging this as is, but we could also factor this out into a separate function (which would be pretty simple to unit test). You could also remove the duplicate code by making the `0, 1` and the error string a var that you set depending on the perspective, but I don't think that will make it nicer.

Comment (marten-seemann) [inline streams_map.go]: I agree that this code isn't particularly nice. I don't have the time to refactor it now, so let's merge it now and do the refactoring later, so we don't block anyone with this.
