### PR TITLE
fix race condition when accessing the encryption level in crypto setup

### LINKED ISSUE #1837: race condition in integration tests
```
------------------------------
Handshake tests rate limiting 
  rejects new connection attempts if connections don't get accepted
  /go/src/github.com/lucas-clemente/quic-go/integrationtests/self/handshake_test.go:228
==================
WARNING: DATA RACE
Write at 0x00c00a21d238 by goroutine 69:
  github.com/lucas-clemente/quic-go/internal/handshake.(*cryptoSetup).SetWriteKey()
      /go/src/github.com/lucas-clemente/quic-go/internal/handshake/crypto_setup.go:454 +0x6ef
  github.com/marten-seemann/qtls.RecordLayer.SetWriteKey-fm()
      /go/pkg/mod/github.com/marten-seemann/qtls@v0.2.2/common.go:568 +0x6e
  github.com/marten-seemann/qtls.(*clientHandshakeStateTLS13).establishHandshakeKeys()
      /go/pkg/mod/github.com/marten-seemann/qtls@v0.2.2/conn.go:198 +0xbbd
  github.com/marten-seemann/qtls.(*clientHandshakeStateTLS13).handshake()
      /go/pkg/mod/github.com/marten-seemann/qtls@v0.2.2/handshake_client_tls13.go:79 +0x4c0
  github.com/marten-seemann/qtls.(*Conn).clientHandshake()
      /go/pkg/mod/github.com/marten-seemann/qtls@v0.2.2/handshake_client.go:203 +0x5e4
  github.com/marten-seemann/qtls.(*Conn).Handshake()
      /go/pkg/mod/github.com/marten-seemann/qtls@v0.2.2/conn.go:1379 +0x13e
  github.com/lucas-clemente/quic-go/internal/handshake.(*cryptoSetup).RunHandshake.func1()
      /go/src/github.com/lucas-clemente/quic-go/internal/handshake/crypto_setup.go:229 +0x94

Previous read at 0x00c00a21d238 by goroutine 272:
  github.com/lucas-clemente/quic-go/internal/handshake.(*cryptoSetup).GetSealer()
      /go/src/github.com/lucas-clemente/quic-go/internal/handshake/crypto_setup.go:501 +0x72
  github.com/lucas-clemente/quic-go.(*packetPacker).PackPacket()
      /go/src/github.com/lucas-clemente/quic-go/packet_packer.go:256 +0xa2
  github.com/lucas-clemente/quic-go.(*session).sendPacket()
      /go/src/github.com/lucas-clemente/quic-go/session.go:1100 +0xce
  github.com/lucas-clemente/quic-go.(*session).sendPackets()
      /go/src/github.com/lucas-clemente/quic-go/session.go:1008 +0x1d0
  github.com/lucas-clemente/quic-go.(*session).run()
      /go/src/github.com/lucas-clemente/quic-go/session.go:426 +0xa8f
  github.com/lucas-clemente/quic-go.(*client).establishSecureConnection.func1()
      /go/src/github.com/lucas-clemente/quic-go/client.go:269 +0x65

Goroutine 69 (running) created at:
  github.com/lucas-clemente/quic-go/internal/handshake.(*cryptoSetup).RunHandshake()
      /go/src/github.com/lucas-clemente/quic-go/internal/handshake/crypto_setup.go:227 +0xbc
  github.com/lucas-clemente/quic-go.(*session).run.func1()
      /go/src/github.com/lucas-clemente/quic-go/session.go:339 +0x62

Goroutine 272 (running) created at:
  github.com/lucas-clemente/quic-go.(*client).establishSecureConnection()
      /go/src/github.com/lucas-clemente/quic-go/client.go:268 +0x8c
  github.com/lucas-clemente/quic-go.(*client).dial()
      /go/src/github.com/lucas-clemente/quic-go/client.go:253 +0x45a
  github.com/lucas-clemente/quic-go.dialContext()
      /go/src/github.com/lucas-clemente/quic-go/client.go:132 +0x23b
  github.com/lucas-clemente/quic-go.DialAddrContext()
      /go/src/github.com/lucas-clemente/quic-go/client.go:83 +0x27a
  github.com/lucas-clemente/quic-go/integrationtests/self_test.glob..func7.6.1()
      /go/src/github.com/lucas-clemente/quic-go/client.go:64 +0x232
  github.com/lucas-clemente/quic-go/integrationtests/self_test.glob..func7.6.5()
      /go/src/github.com/lucas-clemente/quic-go/integrationtests/self/handshake_test.go:229 +0x63
  github.com/onsi/ginkgo/internal/leafnodes.(*runner).runSync()
      /go/pkg/mod/github.com/onsi/ginkgo@v1.8.0/internal/leafnodes/runner.go:113 +0xbd
  github.com/onsi/ginkgo/internal/leafnodes.(*runner).run()
      /go/pkg/mod/github.com/onsi/ginkgo@v1.8.0/internal/leafnodes/runner.go:64 +0x107
  github.com/onsi/ginkgo/internal/leafnodes.(*ItNode).Run()
      /go/pkg/mod/github.com/onsi/ginkgo@v1.8.0/internal/leafnodes/it_node.go:26 +0x87
  github.com/onsi/ginkgo/internal/spec.(*Spec).runSample()
      /go/pkg/mod/github.com/onsi/ginkgo@v1.8.0/internal/spec/spec.go:215 +0x6c6
  github.com/onsi/ginkgo/internal/spec.(*Spec).Run()
      /go/pkg/mod/github.com/onsi/ginkgo@v1.8.0/internal/spec/spec.go:138 +0x142
  github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpec()
      /go/pkg/mod/github.com/onsi/ginkgo@v1.8.0/internal/specrunner/spec_runner.go:200 +0x172
  github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpecs()
      /go/pkg/mod/github.com/onsi/ginkgo@v1.8.0/internal/specrunner/spec_runner.go:170 +0x217
  github.com/onsi/ginkgo/internal/spec.(*Spec).runSample()
      /go/pkg/mod/github.com/onsi/ginkgo@v1.8.0/internal/spec/spec.go:218 +0x758
  github.com/onsi/ginkgo/internal/leafnodes.(*ItNode).Run()
      /go/pkg/mod/github.com/onsi/ginkgo@v1.8.0/internal/leafnodes/it_node.go:26 +0x87
  github.com/onsi/ginkgo/internal/spec.(*Spec).runSample()
      /go/pkg/mod/github.com/onsi/ginkgo@v1.8.0/internal/spec/spec.go:215 +0x6c6
  github.com/onsi/ginkgo/internal/spec.(*Spec).Run()
      /go/pkg/mod/github.com/onsi/ginkgo@v1.8.0/internal/spec/spec.go:138 +0x142
  github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpec()
      /go/pkg/mod/github.com/onsi/ginkgo@v1.8.0/internal/specrunner/spec_runner.go:200 +0x172
  github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpecs()
      /go/pkg/mod/github.com/onsi/ginkgo@v1.8.0/internal/specrunner/spec_runner.go:170 +0x217
  github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpec()
      /go/pkg/mod/github.com/onsi/ginkgo@v1.8.0/internal/specrunner/spec_runner.go:200 +0x172
  github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpecs()
      /go/pkg/mod/github.com/onsi/ginkgo@v1.8.0/internal/specrunner/spec_runner.go:170 +0x217
  github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).Run()
      /go/pkg/mod/github.com/onsi/ginkgo@v1.8.0/internal/specrunner/spec_runner.go:66 +0x140
  github.com/onsi/ginkgo/internal/suite.(*Suite).Run()
      /go/pkg/mod/github.com/onsi/ginkgo@v1.8.0/internal/suite/suite.go:62 +0x6a2
  github.com/onsi/ginkgo.RunSpecsWithCustomReporters()
      /go/pkg/mod/github.com/onsi/ginkgo@v1.8.0/ginkgo_dsl.go:221 +0x33a
  github.com/onsi/ginkgo.RunSpecs()
      /go/pkg/mod/github.com/onsi/ginkgo@v1.8.0/ginkgo_dsl.go:202 +0x99
  github.com/lucas-clemente/quic-go/integrationtests/self_test.TestSelf()
      /go/src/github.com/lucas-clemente/quic-go/integrationtests/self/self_suite_test.go:15 +0xf8
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:865 +0x163
==================
Too long with no output (exceeded 10m0s)
```

### PR DESCRIPTION
**Pull request by marten-seemann**
Fixes #1837.

### CODE REVIEW

File: internal/handshake/crypto_setup.go [hunk 1]
```diff
@@ -501,54 +511,70 @@ func (h *cryptoSetup) SendAlert(alert uint8) {
 	h.alertChan <- alert
 }
 
-func (h *cryptoSetup) GetSealer() (protocol.EncryptionLevel, Sealer) {
+func (h *cryptoSetup) GetSealer() (encLevel protocol.EncryptionLevel, sealer Sealer) {
+	h.mutex.Lock()
```
Comment (lucas-clemente) [inline internal/handshake/crypto_setup.go]: defer unlock?

File: internal/handshake/crypto_setup.go [hunk 2]
```diff
@@ -501,54 +511,70 @@ func (h *cryptoSetup) SendAlert(alert uint8) {
...
-	return protocol.EncryptionInitial, h.initialSealer
+	h.mutex.Unlock()
+	return
 }
 
-func (h *cryptoSetup) GetSealerWithEncryptionLevel(level protocol.EncryptionLevel) (Sealer, error) {
+func (h *cryptoSetup) GetSealerWithEncryptionLevel(level protocol.EncryptionLevel) (sealer Sealer, err error) {
 	errNoSealer := fmt.Errorf("CryptoSetup: no sealer with encryption level %s", level.String())
 
+	h.mutex.Lock()
```
Comment (lucas-clemente) [inline internal/handshake/crypto_setup.go]: defer unlock?

File: internal/handshake/crypto_setup.go [hunk 3]
```diff
@@ -501,54 +511,70 @@ func (h *cryptoSetup) SendAlert(alert uint8) {
...
-		return nil, errNoSealer
+		err = errNoSealer
 	}
+	h.mutex.Unlock()
+	return
 }
 
-func (h *cryptoSetup) GetOpener(level protocol.EncryptionLevel) (Opener, error) {
+func (h *cryptoSetup) GetOpener(level protocol.EncryptionLevel) (opener Opener, err error) {
+	h.mutex.Lock()
```
Comment (lucas-clemente) [inline internal/handshake/crypto_setup.go]: defer unlock?
