### PR TITLE
only delete the acked packet, but none its retransmissions 

### LINKED ISSUE #1256: don't decrease bytes in flight when receiving the ACK for the original packet
As discussed with Subodh in London:
Currently, we're reducing the bytes in flight contributed by a retransmission when receiving an ACk for the original packet. Instead, we should keep some metadata for that packet (i.e. the length of the packet) around, and only subtract the bytes in flight when either receiving an ACK for that packet, or when declaring it lost.

### LINKED ISSUE #1257: keep retransmitted packets, for which the original packet was acked, around for RTT measurements
This will pretty much fall out of the fix for #1256.

### LINKED ISSUE #1276: BUG: packet X already queued for retransmission
After doing some stress testing of quic-go over an LTE connection I hit a BUG in the quic-go code.

```
2018/04/02 00:36:43 Dropping message. name=10.9.0.9:10002, streamId=3, payloadId=54563, topic=id(0x104)/address(0x4b), completedBlocks=37/37, totalFrames=302, maxFramesForStream=1000, entryAge=10.493316298s, maxAge=10s, reason=back-to-front
2018/04/02 00:36:44 Closing session with error: InternalError: sent packet history BUG: packet 2893 already queued for retransmission
2018/04/02 00:36:44 Connection f925334e187678c2 closed.
2018/04/02 00:36:44 Error accepting stream. err=InternalError: sent packet history BUG: packet 2893 already queued for retransmission
2018/04/02 00:36:44 Error encountered, closing peer connection. peerName=10.9.0.9:10002, err= --- at /Users/jnewman/go/src/github.com/narsil-reforged/lattice-mesh/peer.go:491 (Peer.writeAllFrames) ---
Caused by: InternalError: sent packet history BUG: packet 2893 already queued for retransmission
2018/04/02 00:36:44 Error reading next frame, disconnecting peer.. err=InternalError: sent packet history BUG: packet 2893 already queued for retransmission
2018/04/02 00:36:49 Reconnecting...
2018/04/02 00:36:49 Connecting to quic://10.9.0.9:10002
2018/04/02 00:36:49 Starting new connection to 10.9.0.9 ([::]:40374 -> 10.9.0.9:10002), connectionID 35e9b4972a336cf, version gQUIC 39
```

### PR DESCRIPTION
**Pull request by marten-seemann**
Fixes #1256, fixes #1257.
Also fixes #1276.

Those packets are still in flight, until they are either acked or detected lost. We need to keep them in the packet history in order to account them for the bytes in flight.

### CODE REVIEW

**Comment by marten-seemann** [comment]
@lucas-clemente: I think I found what cause #1276, and that should be fixed now.

File: internal/ackhandler/sent_packet_handler.go [hunk 1]
```diff
@@ -503,7 +506,10 @@ func (h *sentPacketHandler) queueHandshakePacketsForRetransmission() error {
 }
 
 func (h *sentPacketHandler) queuePacketForRetransmission(p *Packet) error {
-	if _, err := h.packetHistory.QueuePacketForRetransmission(p.PacketNumber); err != nil {
+	if p.cannotBeRetransmitted {
+		return fmt.Errorf("sent packet handler BUG: packet %d already queued for retransmission", p.PacketNumber)
+	}
+	if err := h.packetHistory.MarkCannotBeRetransmitted(p.PacketNumber); err != nil {
```
Comment (lucas-clemente) [inline internal/ackhandler/sent_packet_handler.go]: You could move stopRetransmissionsFor into MarkCannotBeRetransmitted and call that from here without changing behavior IIUC. That would decrease coupling between the SPH and history.

Comment (marten-seemann) [reply internal/ackhandler/sent_packet_handler.go]: It would work, but it would be really weird, since we're calling `MarkCannotBeRetransmitted` from `queuePacketForRetransmission` as well.
