### PR TITLE
fix flaky session test

### LINKED ISSUE #603: flaky session test on AppVeyor
```
+! Panic [0.013 seconds]
Session [It] closes when crypto stream errors 
c:/gopath/src/github.com/lucas-clemente/quic-go/session_test.go:1170
  Test Panicked
  interface conversion: error is nil, not *qerr.QuicError
  C:/go/src/runtime/panic.go:489
  Full Stack Trace
  	C:/go/src/runtime/panic.go:489 +0x22a
  github.com/lucas-clemente/quic-go.glob..func11.20()
  	c:/gopath/src/github.com/lucas-clemente/quic-go/session_test.go:1169 +0x423
  github.com/onsi/ginkgo/internal/leafnodes.(*runner).runSync(0x169fafc0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  	c:/gopath/src/github.com/lucas-clemente/quic-go/quic_suite_test.go:12 +0x53
  testing.tRunner(0x17708d80, 0x83b3ec)
  	C:/go/src/testing/testing.go:657 +0x7e
  created by testing.(*T).Run
  	C:/go/src/testing/testing.go:697 +0x242
```

### PR DESCRIPTION
**Pull request by marten-seemann**
Fixes #603.

This test can be simplified (and made race-free) by using that `session.run()` now returns an error.

### CODE REVIEW

File: session_test.go [hunk 1]
```diff
@@ -1166,17 +1166,17 @@ var _ = Describe("Session", func() {
...
+		}()
+		err := sess.handleStreamFrame(&frames.StreamFrame{
 			StreamID: 1,
 			Data:     []byte("4242\x00\x00\x00\x00"),
 		})
 		Expect(err).NotTo(HaveOccurred())
-		Eventually(func() bool { return atomic.LoadUint32(&sess.closed) != 0 }).Should(BeTrue())
-		_, err = s.Write([]byte{})
-		Expect(err.(*qerr.QuicError).ErrorCode).To(Equal(qerr.InvalidCryptoMessageType))
+		Eventually(func() error { return runErr }).Should(HaveOccurred())
```
Comment (lucas-clemente) [inline session_test.go]: I don't think you need the lambda here.

Comment (marten-seemann) [inline session_test.go]: True.

Comment (marten-seemann) [inline session_test.go]: No, not true. `runErr` is set in the goroutine running `session.run()`.
