### PR TITLE
increase RTT and time constraints in handshake RTT tests

### LINKED ISSUE #638: RTT Test is flaky
```
• Failure [1.039 seconds]
Handshake integration tets [It] is forward-secure after 3 RTTs 
/home/travis/gopath/src/github.com/lucas-clemente/quic-go/integrationtests/handshake/rtt.go:90
  Expected
      <time.Duration>: 1036622990
  to be <
      <time.Duration>: 1000000000
  /home/travis/gopath/src/github.com/lucas-clemente/quic-go/integrationtests/handshake/rtt.go:66
  Full Stack Trace
  	/home/travis/gopath/src/github.com/onsi/gomega/internal/assertion/assertion.go:69 +0x1ed
  github.com/onsi/gomega/internal/assertion.(*Assertion).To(0xc420594440, 0x9d1220, 0xc4205fc4e0, 0x0, 0x0, 0x0, 0xc4205fc4b0)
  	/home/travis/gopath/src/github.com/onsi/gomega/internal/assertion/assertion.go:35 +0xae
  github.com/lucas-clemente/quic-go/integrationtests/handshake.glob..func1.4(0x3)
  	/home/travis/gopath/src/github.com/lucas-clemente/quic-go/integrationtests/handshake/rtt.go:66 +0x32d
  github.com/lucas-clemente/quic-go/integrationtests/handshake.glob..func1.6()
  	/home/travis/gopath/src/github.com/lucas-clemente/quic-go/integrationtests/handshake/rtt.go:89 +0x205
  github.com/onsi/ginkgo/internal/leafnodes.(*runner).runSync(0xc42006ecc0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  	/home/travis/gopath/src/github.com/lucas-clemente/quic-go/integrationtests/handshake/handshaketests_suite_test.go:12 +0x64
  testing.tRunner(0xc420098300, 0x841070)
  	/home/travis/.gimme/versions/go1.7.5.linux.amd64/src/testing/testing.go:610 +0x81
  created by testing.(*T).Run
  	/home/travis/.gimme/versions/go1.7.5.linux.amd64/src/testing/testing.go:646 +0x2ec
```

### PR DESCRIPTION
**Pull request by marten-seemann**
Hopefully fixes #638.

### CODE REVIEW

File: integrationtests/handshake/rtt.go [hunk 1]
```diff
@@ -62,7 +62,7 @@ var _ = Describe("Handshake integration tets", func() {
 		expectedDuration := time.Duration(num) * rtt
 		Expect(testDuration).To(SatisfyAll(
 			BeNumerically(">=", expectedDuration),
-			BeNumerically("<", expectedDuration+rtt/3),
+			BeNumerically("<", expectedDuration+rtt/2),
```
Comment (lucas-clemente) [inline integrationtests/handshake/rtt.go]: To be fair, we can probably go to `< expected duration + rtt` here, and the assertion would still be valid.

Comment (marten-seemann) [inline integrationtests/handshake/rtt.go]: Probably. Let's see how this works out on our CIs first, I'd prefer to keep stricter constraints, if possible.
