### PR TITLE
make flow control stricter when receiving final offsets

### LINKED ISSUE #382: check for StreamDataAfterTermination errors
After half-closing (remote) a stream, either by receiving a `RstStreamFrames` or by receiving a FIN, an incorrect implementation of the peer could still send `StreamFrames` with a higher offset. At the moment, we're simply ignoring all `StreamFrames` on closed streams.
We should send a `StreamDataAfterTermination` error instead.

### PR DESCRIPTION
**Pull request by marten-seemann**
1. Reject STREAM frames with a higher offset than a previously received highest offset.
2. Reject inconsistent final offsets.

Fixes #382.

### CODE REVIEW

File: internal/flowcontrol/stream_flow_controller.go [hunk 1]
```diff
@@ -52,6 +52,11 @@ func (c *streamFlowController) UpdateHighestReceived(byteOffset protocol.ByteCou
 	c.mutex.Lock()
 	defer c.mutex.Unlock()
 
+	// when receiving a final offset, check that this final offset is consistent with a final offset we might have received earlier
+	if final && c.receivedFinalOffset && byteOffset != c.highestReceived {
+		return qerr.Error(qerr.StreamDataAfterTermination, fmt.Sprintf("Received inconsistent final offset for stream %d (%d vs %d bytes)", c.streamID, byteOffset, c.highestReceived))
```
Comment (lucas-clemente) [inline internal/flowcontrol/stream_flow_controller.go]: Nit: "old: 42, new: 23" instead of "42 vs 23".
