### PR TITLE
fix packet buffer usage when handling coalesced packets

### LINKED ISSUE #1807: only put back packet buffer after processing the whole coalesced packet
Tests on CI fail with:
```
Session sending packets packet pacing 
  sends multiple packets one by one immediately
  /home/travis/gopath/src/github.com/lucas-clemente/quic-go/session_test.go:868
•! Panic [1.113 seconds]
Session
/home/travis/gopath/src/github.com/lucas-clemente/quic-go/session_test.go:65
  sending packets
  /home/travis/gopath/src/github.com/lucas-clemente/quic-go/session_test.go:725
    packet pacing
    /home/travis/gopath/src/github.com/lucas-clemente/quic-go/session_test.go:857
      sends multiple packets one by one immediately [It]
      /home/travis/gopath/src/github.com/lucas-clemente/quic-go/session_test.go:868
      Test Panicked
      negative packetBuffer refCount
      /home/travis/.gimme/versions/go1.12.linux.amd64/src/runtime/panic.go:522
      Full Stack Trace
      	/home/travis/gopath/pkg/mod/github.com/onsi/ginkgo@v1.7.0/internal/codelocation/code_location.go:14 +0x78
      github.com/onsi/ginkgo.GinkgoRecover()
      	/home/travis/gopath/pkg/mod/github.com/onsi/ginkgo@v1.7.0/ginkgo_dsl.go:278 +0x68
      panic(0x98a4e0, 0xb28650)
      	/home/travis/.gimme/versions/go1.12.linux.amd64/src/runtime/panic.go:522 +0x1b5
      github.com/lucas-clemente/quic-go.(*packetBuffer).Release(0xc00048a780)
      	/home/travis/gopath/src/github.com/lucas-clemente/quic-go/buffer_pool.go:34 +0xe4
      github.com/lucas-clemente/quic-go.(*session).sendPackedPacket(0xc0002c0900, 0xc0002c8a80, 0x0, 0x0)
      	/home/travis/gopath/src/github.com/lucas-clemente/quic-go/session.go:1127 +0xc7
      github.com/lucas-clemente/quic-go.(*session).sendPacket(0xc0002c0900, 0x1, 0x0, 0xc0005c6cf0)
      	/home/travis/gopath/src/github.com/lucas-clemente/quic-go/session.go:1118 +0x135
      github.com/lucas-clemente/quic-go.(*session).sendPackets(0xc0002c0900, 0x590b52197, 0xff7b60)
      	/home/travis/gopath/src/github.com/lucas-clemente/quic-go/session.go:1009 +0x197
      github.com/lucas-clemente/quic-go.(*session).run(0xc0002c0900, 0x0, 0x0)
      	/home/travis/gopath/src/github.com/lucas-clemente/quic-go/session.go:421 +0x547
      github.com/lucas-clemente/quic-go.glob..func22.8.10.2.1(0xc000010630, 0xc000010608, 0xc000038600)
      	/home/travis/gopath/src/github.com/lucas-clemente/quic-go/session_test.go:880 +0xc2
      created by github.com/lucas-clemente/quic-go.glob..func22.8.10.2
      	/home/travis/gopath/src/github.com/lucas-clemente/quic-go/session_test.go:877 +0x60a
```

### PR DESCRIPTION
**Pull request by marten-seemann**
Fixes #1807.

### CODE REVIEW

File: buffer_pool.go [hunk 1]
```diff
@@ -22,21 +22,39 @@ func (b *packetBuffer) Split() {
...
 	if b.refCount == 0 {
-		bufferPool.Put(b)
+		b.putBack()
+	}
+}
+
+// Release puts back the packet buffer into the pool.
+// It should be called when processing is definitely finished.
+func (b *packetBuffer) Release() {
+	b.refCount--
```
Comment (lucas-clemente) [inline buffer_pool.go]: Call Decrement here?

Comment (marten-seemann) [reply buffer_pool.go]: Done.
