### PR TITLE
fix race conditions in new streams maps

### LINKED ISSUE #1188: race condition in new streams map
```
==================
WARNING: DATA RACE
Read at 0x00c425756600 by goroutine 233:
  github.com/lucas-clemente/quic-go.(*incomingBidiStreamsMap).GetOrOpenStream()
      /Users/marten/src/go/src/github.com/lucas-clemente/quic-go/streams_map_incoming_bidi.go:78 +0x8e
  github.com/lucas-clemente/quic-go.(*streamsMap).GetOrOpenReceiveStream()
      /Users/marten/src/go/src/github.com/lucas-clemente/quic-go/streams_map.go:167 +0xa5
  github.com/lucas-clemente/quic-go.(*session).handleStreamFrame()
      /Users/marten/src/go/src/github.com/lucas-clemente/quic-go/session.go:615 +0x1cc
  github.com/lucas-clemente/quic-go.(*session).handleFrames()
      /Users/marten/src/go/src/github.com/lucas-clemente/quic-go/session.go:560 +0x347
  github.com/lucas-clemente/quic-go.(*session).handlePacketImpl()
      /Users/marten/src/go/src/github.com/lucas-clemente/quic-go/session.go:551 +0x708
  github.com/lucas-clemente/quic-go.(*session).run()
      /Users/marten/src/go/src/github.com/lucas-clemente/quic-go/session.go:385 +0x13ba
  github.com/lucas-clemente/quic-go.(*server).runHandshakeAndSession.func1()
      /Users/marten/src/go/src/github.com/lucas-clemente/quic-go/server.go:390 +0x41

Previous write at 0x00c425756600 by goroutine 507:
  github.com/lucas-clemente/quic-go.(*incomingBidiStreamsMap).GetOrOpenStream()
      /Users/marten/src/go/src/github.com/lucas-clemente/quic-go/streams_map_incoming_bidi.go:96 +0x217
  github.com/lucas-clemente/quic-go.(*streamsMap).GetOrOpenSendStream()
      /Users/marten/src/go/src/github.com/lucas-clemente/quic-go/streams_map.go:183 +0xa5
  github.com/lucas-clemente/quic-go.(*session).GetOrOpenStream()
      /Users/marten/src/go/src/github.com/lucas-clemente/quic-go/session.go:913 +0x7b
  github.com/lucas-clemente/quic-go/h2quic.(*Server).handleRequest()
      /Users/marten/src/go/src/github.com/lucas-clemente/quic-go/h2quic/server.go:178 +0x455
  github.com/lucas-clemente/quic-go/h2quic.(*Server).handleHeaderStream()
      /Users/marten/src/go/src/github.com/lucas-clemente/quic-go/h2quic/server.go:136 +0x26c

Goroutine 233 (running) created at:
  github.com/lucas-clemente/quic-go.(*server).runHandshakeAndSession()
      /Users/marten/src/go/src/github.com/lucas-clemente/quic-go/server.go:389 +0x6e
  github.com/lucas-clemente/quic-go.(*server).setupTLS.func1()
      /Users/marten/src/go/src/github.com/lucas-clemente/quic-go/server.go:145 +0x7e

Goroutine 507 (running) created at:
  github.com/lucas-clemente/quic-go/h2quic.(*Server).serveImpl()
      /Users/marten/src/go/src/github.com/lucas-clemente/quic-go/h2quic/server.go:120 +0x27f
  github.com/lucas-clemente/quic-go/h2quic.(*Server).Serve()
      /Users/marten/src/go/src/github.com/lucas-clemente/quic-go/h2quic/server.go:84 +0x7f
  github.com/lucas-clemente/quic-go/integrationtests/tools/testserver.StartQuicServer.func1()
      /Users/marten/src/go/src/github.com/lucas-clemente/quic-go/integrationtests/tools/testserver/server.go:103 +0x80
==================
```

and

```
==================
WARNING: DATA RACE
Read at 0x00c427550058 by goroutine 411:
  github.com/lucas-clemente/quic-go.(*outgoingBidiStreamsMap).GetStream()
      /Users/marten/src/go/src/github.com/lucas-clemente/quic-go/streams_map_outgoing_bidi.go:88 +0x54
  github.com/lucas-clemente/quic-go.(*streamsMap).GetOrOpenSendStream()
      /Users/marten/src/go/src/github.com/lucas-clemente/quic-go/streams_map.go:181 +0x16b
  github.com/lucas-clemente/quic-go.(*streamFramer).maybePopNormalFrames()
      /Users/marten/src/go/src/github.com/lucas-clemente/quic-go/stream_framer.go:120 +0x1f8
  github.com/lucas-clemente/quic-go.(*streamFramer).PopStreamFrames()
      /Users/marten/src/go/src/github.com/lucas-clemente/quic-go/stream_framer.go:57 +0xa1
  github.com/lucas-clemente/quic-go.(*packetPacker).composeNextPacket()
      /Users/marten/src/go/src/github.com/lucas-clemente/quic-go/packet_packer.go:273 +0x485
  github.com/lucas-clemente/quic-go.(*packetPacker).PackPacket()
      /Users/marten/src/go/src/github.com/lucas-clemente/quic-go/packet_packer.go:159 +0x254
  github.com/lucas-clemente/quic-go.(*session).sendPacket()
      /Users/marten/src/go/src/github.com/lucas-clemente/quic-go/session.go:859 +0x8c0
  github.com/lucas-clemente/quic-go.(*session).sendPackets()
      /Users/marten/src/go/src/github.com/lucas-clemente/quic-go/session.go:766 +0x138
  github.com/lucas-clemente/quic-go.(*session).run()
      /Users/marten/src/go/src/github.com/lucas-clemente/quic-go/session.go:439 +0x723
  github.com/lucas-clemente/quic-go.(*server).runHandshakeAndSession.func1()
      /Users/marten/src/go/src/github.com/lucas-clemente/quic-go/server.go:390 +0x41

Previous write at 0x00c427550058 by goroutine 123:
  github.com/lucas-clemente/quic-go.(*outgoingBidiStreamsMap).openStreamImpl()
      /Users/marten/src/go/src/github.com/lucas-clemente/quic-go/streams_map_outgoing_bidi.go:83 +0x2d1
  github.com/lucas-clemente/quic-go.(*outgoingBidiStreamsMap).OpenStreamSync()
      /Users/marten/src/go/src/github.com/lucas-clemente/quic-go/streams_map_outgoing_bidi.go:59 +0x97
  github.com/lucas-clemente/quic-go.(*streamsMap).OpenStreamSync()
      /Users/marten/src/go/src/github.com/lucas-clemente/quic-go/streams_map.go:128 +0x52
  github.com/lucas-clemente/quic-go.(*session).OpenStreamSync()
      /Users/marten/src/go/src/github.com/lucas-clemente/quic-go/session.go:939 +0x57
  github.com/lucas-clemente/quic-go/integrationtests/self_test.glob..func3.1.3()
      /Users/marten/src/go/src/github.com/lucas-clemente/quic-go/integrationtests/self/stream_test.go:47 +0x214
  github.com/lucas-clemente/quic-go/integrationtests/self_test.glob..func3.1.7.1()
      /Users/marten/src/go/src/github.com/lucas-clemente/quic-go/integrationtests/self/stream_test.go:130 +0x19e

Goroutine 411 (running) created at:
  github.com/lucas-clemente/quic-go.(*server).runHandshakeAndSession()
      /Users/marten/src/go/src/github.com/lucas-clemente/quic-go/server.go:389 +0x6e
  github.com/lucas-clemente/quic-go.(*server).setupTLS.func1()
      /Users/marten/src/go/src/github.com/lucas-clemente/quic-go/server.go:145 +0x7e

Goroutine 123 (running) created at:
  github.com/lucas-clemente/quic-go/integrationtests/self_test.glob..func3.1.7()
      /Users/marten/src/go/src/github.com/lucas-clemente/quic-go/integrationtests/self/stream_test.go:120 +0xe6
  github.com/onsi/ginkgo/internal/leafnodes.(*runner).runSync()
      /Users/marten/src/go/src/github.com/onsi/ginkgo/internal/leafnodes/runner.go:109 +0xbb
  github.com/onsi/ginkgo/internal/leafnodes.(*runner).run()
      /Users/marten/src/go/src/github.com/onsi/ginkgo/internal/leafnodes/runner.go:63 +0x17a
  github.com/onsi/ginkgo/internal/leafnodes.(*ItNode).Run()
      /Users/marten/src/go/src/github.com/onsi/ginkgo/internal/leafnodes/it_node.go:25 +0xa0
  github.com/onsi/ginkgo/internal/spec.(*Spec).runSample()
      /Users/marten/src/go/src/github.com/onsi/ginkgo/internal/spec/spec.go:176 +0x741
  github.com/onsi/ginkgo/internal/spec.(*Spec).Run()
      /Users/marten/src/go/src/github.com/onsi/ginkgo/internal/spec/spec.go:127 +0x112
  github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpec()
      /Users/marten/src/go/src/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:198 +0x173
  github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpecs()
      /Users/marten/src/go/src/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:168 +0x5f7
  github.com/onsi/ginkgo/internal/spec.(*Spec).runSample()
      /Users/marten/src/go/src/github.com/onsi/ginkgo/internal/spec/spec.go:177 +0x7de
  github.com/onsi/ginkgo/internal/leafnodes.(*ItNode).Run()
      /Users/marten/src/go/src/github.com/onsi/ginkgo/internal/leafnodes/it_node.go:25 +0xa0
  github.com/onsi/ginkgo/internal/spec.(*Spec).runSample()
      /Users/marten/src/go/src/github.com/onsi/ginkgo/internal/spec/spec.go:176 +0x741
  github.com/onsi/ginkgo/internal/spec.(*Spec).Run()
      /Users/marten/src/go/src/github.com/onsi/ginkgo/internal/spec/spec.go:127 +0x112
  github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpec()
      /Users/marten/src/go/src/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:198 +0x173
  github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpecs()
      /Users/marten/src/go/src/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:168 +0x5f7
  github.com/onsi/ginkgo/internal/spec.(*Spec).runSample()
      /Users/marten/src/go/src/github.com/onsi/ginkgo/internal/spec/spec.go:176 +0x741
  github.com/onsi/ginkgo/internal/spec.(*Spec).Run()
      /Users/marten/src/go/src/github.com/onsi/ginkgo/internal/spec/spec.go:127 +0x112
  github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpec()
      /Users/marten/src/go/src/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:198 +0x173
  github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpecs()
      /Users/marten/src/go/src/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:168 +0x5f7
  github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpec()
      /Users/marten/src/go/src/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:198 +0x173
  github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpecs()
      /Users/marten/src/go/src/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:168 +0x5f7
  github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpec()
      /Users/marten/src/go/src/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:198 +0x173
  github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpecs()
      /Users/marten/src/go/src/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:168 +0x5f7
  github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).Run()
      /Users/marten/src/go/src/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:64 +0x103
  github.com/onsi/ginkgo/internal/suite.(*Suite).Run()
      /Users/marten/src/go/src/github.com/onsi/ginkgo/internal/suite/suite.go:62 +0x3b9
  github.com/onsi/ginkgo.RunSpecsWithCustomReporters()
      /Users/marten/src/go/src/github.com/onsi/ginkgo/ginkgo_dsl.go:218 +0x310
  github.com/onsi/ginkgo.RunSpecs()
      /Users/marten/src/go/src/github.com/onsi/ginkgo/ginkgo_dsl.go:199 +0xc1
  github.com/lucas-clemente/quic-go/integrationtests/self_test.TestSelf()
      /Users/marten/src/go/src/github.com/lucas-clemente/quic-go/integrationtests/self/self_suite_test.go:14 +0x85
  testing.tRunner()
      /usr/local/Cellar/go/1.10/libexec/src/testing/testing.go:777 +0x16d
==================
```

### PR DESCRIPTION
**Pull request by marten-seemann**
Fixes #1188.

I avoided using `defer` here, due to the performance penalty we'd pay for that on the stream getter functions, which are called very frequently.

### CODE REVIEW

File: streams_map_incoming_bidi.go [hunk 1]
```diff
@@ -69,18 +69,20 @@ func (m *incomingBidiStreamsMap) AcceptStream() (streamI, error) {
...
 	// if the id is smaller than the highest we accepted
 	// * this stream exists in the map, and we can return it, or
 	// * this stream was already closed, then we can return the nil
 	if id <= m.highestStream {
-		m.mutex.RLock()
 		s := m.streams[id]
 		m.mutex.RUnlock()
 		return s, nil
 	}
+	m.mutex.RUnlock()
```
Comment (lucas-clemente) [inline streams_map_incoming_bidi.go]: I think there's another race here. You need to do these checks again once you've acquired the write lock, as another thread might have just completed the write locked block.

File: streams_map_incoming_generic.go [hunk 2]
```diff
@@ -67,18 +67,20 @@ func (m *incomingItemsMap) AcceptStream() (item, error) {
...
 	// if the id is smaller than the highest we accepted
 	// * this stream exists in the map, and we can return it, or
 	// * this stream was already closed, then we can return the nil
 	if id <= m.highestStream {
-		m.mutex.RLock()
 		s := m.streams[id]
 		m.mutex.RUnlock()
 		return s, nil
 	}
+	m.mutex.RUnlock()
```
Comment (lucas-clemente) [inline streams_map_incoming_generic.go]: Same as above?

File: streams_map_incoming_uni.go [hunk 3]
```diff
@@ -69,18 +69,20 @@ func (m *incomingUniStreamsMap) AcceptStream() (receiveStreamI, error) {
...
 	// if the id is smaller than the highest we accepted
 	// * this stream exists in the map, and we can return it, or
 	// * this stream was already closed, then we can return the nil
 	if id <= m.highestStream {
-		m.mutex.RLock()
 		s := m.streams[id]
 		m.mutex.RUnlock()
 		return s, nil
 	}
+	m.mutex.RUnlock()
```
Comment (lucas-clemente) [inline streams_map_incoming_uni.go]: Same as above?

File: streams_map_incoming_bidi.go (hunk 1 above)
Comment (marten-seemann) [reply streams_map_incoming_bidi.go]: I don't think this is necessary here.
`m.maxStream` can only be increased (by `DeleteStream`), so the id is valid for the first check (`id <= m.maxStream`), it will definitely be valid if `m.maxStream` is increased.
Regarding `m.highestStream`, that variable is only read by other methods, never written, so the value can't change.

Comment (lucas-clemente) [reply streams_map_incoming_bidi.go]: Then add a comment stating that. That makes it clear that you thought about it, and ensures we don't forget about this assumption if we make later changes.

Comment (marten-seemann) [reply streams_map_incoming_bidi.go]: Done.

Comment (lucas-clemente) [reply streams_map_incoming_bidi.go]: Does the same apply for the other two locations?

Comment (marten-seemann) [reply streams_map_incoming_bidi.go]: The other two are auto generated from this one.

Comment (lucas-clemente) [reply streams_map_incoming_bidi.go]: Ah, right 🙄
