### PR TITLE
various amplification limit fixes

### LINKED ISSUE #3053: investigate recent loss recovery change
https://github.com/quicwg/base-drafts/pull/4831/

### PR DESCRIPTION
**Pull request by marten-seemann**
Fixes #3053.

1. When becoming amplification limited, we don't need to set a loss recovery timer. All we can do at that point is wait for a packet from the client to arrive.
2. Once that packet arrives, we need to restart the loss recovery timer.

### CODE REVIEW

File: internal/ackhandler/sent_packet_handler.go [hunk 1]
```diff
@@ -490,20 +496,34 @@ func (h *sentPacketHandler) setLossDetectionTimer() {
...
+			}
 		}
 		return
 	}
 
 	// PTO alarm
 	ptoTime, encLevel := h.getPTOTimeAndSpace()
 	h.alarm = ptoTime
-	if h.tracer != nil && h.alarm != oldAlarm {
+	if h.tracer != nil { //&& h.alarm != oldAlarm {
```
Comment (lucas-clemente) [inline internal/ackhandler/sent_packet_handler.go:526]: Nit

**Review by lucas-clemente — APPROVED** [review]
