### PR TITLE
sendQueue: ignore "datagram too large" error

### LINKED ISSUE #3273: mtu_discoverer: INTERNAL_ERROR on Windows
With Path MTU Discovery enabled on windows, an error is thrown:
```
{"level":"error","ts":1631441093.781284,"caller":"peer/quic.go:65","msg":"accepting stream from peers","PeerID":11890175577191328473,"Initiator":true,"error":"INTERNAL_ERROR: write udp [::]:62885->[redacted]:1111: wsasendto: A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to receive a datagram into was smaller than the datagram itself.","stacktrace":"github.com/zllovesuki/t/peer.(*QUIC).Start\n\tC:/Users/Ultium/code/t/peer/quic.go:65"}
```

`*quic.Config` is as follows:
```
&quic.Config{
	KeepAlive:               true,
	HandshakeIdleTimeout:    time.Second * 3,
	MaxIdleTimeout:          time.Second * 15,
}
```

Curiously, the INTERNAL_ERROR is not raised immediately. I was able to `AcceptStream(ctx)`/`OpenStream()` to do application layer handshake, then the quic session is passed to a different struct to do `AcceptStream(ctx)` in a loop. The error is then raised.

### PR DESCRIPTION
**Pull request by zllovesuki**
This commit introduces additional platform-dependent checking when the
kernel returns an error. Previously, the session is terminated when
PingFrame sends a discovery packet larger than the limit. With this
commit, the error is checked, and if it is "datagram too large", the
error is ignored.

Additionally,
1. This commit re-enables MTU discovery on Windows unless it
is disabled explicitly by user (Undo #3276),
2. Set IP_DONTFRAGMENT and IPV6_DONTFRAG with error checking on Windows,
   and
3. Set IP_MTU_DISCOVERY to PMTUDISC_DO for both IPv4 and IPv6 on Linux
   so that the kernel will return "message too long".

Fixes #3273 #3327

### CODE REVIEW

**Comment by zllovesuki** [comment]
Hooking into `onLost` and `onAcked` shows that MTU was able to increase with this commit.
```
		OnLost: func(wire.Frame) {
			f.probeInFlight = false
			f.max = size
			fmt.Printf("MTU DISCOVERY GONE: %+v\n", f)
		},
		OnAcked: func(wire.Frame) {
			f.probeInFlight = false
			f.current = size
			f.mtuIncreased(size)
			fmt.Printf("MTU DISCOVERY GOT: %+v\n", f)
		},
```

On a connection via WireGuard that causes MTU to be reduced:
```
MTU DISCOVERY GOT: &{lastProbeTime:{wall:13869129029832926620 ext:622940201 loc:0x171a600} probeInFlight:false mtuIncreased:0x102ede0 rttStats:0xc0000d43c0 current:1352 max:1452}
MTU DISCOVERY GONE: &{lastProbeTime:{wall:13869129030004107620 ext:794121201 loc:0x171a600} probeInFlight:false mtuIncreased:0x102ede0 rttStats:0xc0000d43c0 current:1352 max:1402}
MTU DISCOVERY GOT: &{lastProbeTime:{wall:13869129038891791436 ext:9018128601 loc:0x171a600} probeInFlight:false mtuIncreased:0x102ede0 rttStats:0xc0000d43c0 current:1377 max:1402}
MTU DISCOVERY GOT: &{lastProbeTime:{wall:13869129039070470136 ext:9196807301 loc:0x171a600} probeInFlight:false mtuIncreased:0x102ede0 rttStats:0xc0000d43c0 current:1389 max:1402}
```

On vanilla connection:
```
MTU DISCOVERY GOT: &{lastProbeTime:{wall:13869129101720445128 ext:470531601 loc:0x11ba600} probeInFlight:false mtuIncreased:0xacede0 rttStats:0xc00002c540 current:1352 max:1452}
MTU DISCOVERY GOT: &{lastProbeTime:{wall:13869129101906285828 ext:656372301 loc:0x11ba600} probeInFlight:false mtuIncreased:0xacede0 rttStats:0xc00002c540 current:1402 max:1452}
MTU DISCOVERY GOT: &{lastProbeTime:{wall:13869129102166036452 ext:842381101 loc:0x11ba600} probeInFlight:false mtuIncreased:0xacede0 rttStats:0xc00002c540 current:1427 max:1452}
MTU DISCOVERY GOT: &{lastProbeTime:{wall:13869129102354195652 ext:1030540301 loc:0x11ba600} probeInFlight:false mtuIncreased:0xacede0 rttStats:0xc00002c540 current:1439 max:1452}
```

File: err_size.go [hunk 1]
```diff
@@ -0,0 +1 @@
+package quic
```
Comment (marten-seemann) [inline err_size.go:1]: We probably don't need this file?

File: send_queue.go [hunk 2]
```diff
@@ -64,7 +64,9 @@ func (h *sendQueue) Run() error {
 			shouldClose = true
 		case p := <-h.queue:
 			if err := h.conn.Write(p.Data); err != nil {
-				return err
+				if !isMsgSizeErr(err) {
```
Comment (marten-seemann) [inline send_queue.go:67]: Can you add a comment here, explaining
1. That this makes it possible to run MTU discovery
1. That we're returning MTU errors from the kernel (and that the kernel might act upon ICMP packets)
1. That the packet will be detected lost by loss recovery (eventually)

File: conn_windows.go [hunk 3]
```diff
@@ -13,7 +13,7 @@ import (
 )
 
 const (
-	disablePathMTUDiscovery = true
+	disablePathMTUDiscovery = false
```
Comment (marten-seemann) [inline conn_windows.go:16]: We can remove this const (and the associated code path now), right? It's set to `false` on all architectures.

**Review by marten-seemann — APPROVED** [review]
This looks very clean. Thank you @zllovesuki!
Just a few nits.

File: err_size.go (hunk 1 above)
Comment (zllovesuki) [reply err_size.go:1]: I think the `// +build unix` flag is not yet merged on Go upstream yet. I need to make some changes.

Comment (zllovesuki) [reply err_size.go:4]: ok, i moved _generic into this file instead.

File: conn_windows.go (hunk 3 above)
Comment (zllovesuki) [reply conn_windows.go]: undo previous PR that added the checks.

**Comment by zllovesuki** [comment]
Unfortunately I couldn't properly test the commit on Linux or FreeBSD as they are running in Hyper-V. If someone can help with testing those (e.g. vanilla vs via VPN so reduced MTU).

On illumos/amd64 it produces no regression (good).

**Comment by tobyxdd** [comment]
Perhaps we should disable PMTUD for all platforms, except for those that we have an implementation that turns on DF bit? This PR only covers Windows and Linux. Does anyone know the default behavior and how to turn on DF on platforms like macOS, FreeBSD, etc.?

**Comment by zllovesuki** [comment]
That is certainly an idea, however I wold _really_ prefer if we can add more support for those OSes. MTU of 1300 vs 1400, that's extra 10 packets to send for 1000 bytes of data (!). Literally making the internet a better place if we can make it more efficient.

**Comment by tobyxdd** [comment]
@marten-seemann  care to comment on this?

I can confirm that this works fine on Linux & Windows.

**Comment by tobyxdd** [comment]
https://gist.github.com/tobyxdd/1964cc8d559fb367010c80c1dafee1b1

This patch (based on the code of current PR) moves the set DF implementation to a separate file for each platform & the passed-in `PacketConn` no longer needs to be an `OOBCapablePacketConn` - it only needs to have `SyscallConn`.

This is useful when the `PacketConn` is not a `net.UDPConn` for whatever reason (e.g. in [my project](https://github.com/HyNetwork/hysteria) where there's an added layer of obfuscation on top of `UDPConn`)

**Review by marten-seemann — APPROVED** [review]
LGTM. Thank you @zllovesuki!

**Comment by zllovesuki** [comment]
> [gist.github.com/tobyxdd/1964cc8d559fb367010c80c1dafee1b1](https://gist.github.com/tobyxdd/1964cc8d559fb367010c80c1dafee1b1)
> 
> This patch (based on the code of current PR) moves the set DF implementation to a separate file for each platform & the passed-in `PacketConn` no longer needs to be an `OOBCapablePacketConn` - it only needs to have `SyscallConn`.
> 
> This is useful when the `PacketConn` is not a `net.UDPConn` for whatever reason (e.g. in [my project](https://github.com/HyNetwork/hysteria) where there's an added layer of obfuscation on top of `UDPConn`)

Do you think we should abstract this part out? @marten-seemann

**Comment by marten-seemann** [comment]
Yes, but let's do that in a follow-up PR. Makes reviewing easier.

**Comment by zllovesuki** [comment]
/unrelated

I got my hands on an ppc64le machine to test (courtesy of folks at https://openpower.ic.unicamp.br/minicloud/), and it seems like quic-go works quite well on ppc64le as well (on Debian/ppc64el at least).

**Comment by zllovesuki** [comment]
@tobyxdd would you mind submitting a new PR with your patch after this PR has been merged?

**Comment by tobyxdd** [comment]
> If we are going to ignore the ICMP PTB message anyway, why not just set `IP(V6)_MTU_DISCOVER` to `IP_PMTUDISC_PROBE`? This disables IP fragmentation and allows you to send UDP packets exceeding the system cached PMTU without returning `-EMSGSIZE`.
> 
> `IP_PMTUDISC_PROBE` is supported by Linux and all versions of Windows that are still supported by Microsoft. Unless supporting outdated Windows systems like Windows 7 is a goal, `IP(V6)_MTU_DISCOVER` should be preferred over `IP(V6)_DONTFRAGMENT`.

https://docs.microsoft.com/en-us/windows/win32/winsock/ipproto-ip-socket-options#windows-support-for-ip_proto-options

According to MS docs, neither `IP_PMTUDISC_PROBE` nor `IP_MTU_DISCOVER` is available on Windows

**Comment by database64128** [comment]
@tobyxdd The link you referenced directly contradicts what you said. Just press Ctrl + F and search `IP_MTU_DISCOVER`.

If you have any Windows device around, open `"C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared\ws2ipdef.h"` and go to line 121. Everything I mentioned is right there.

I suggested using `IP_MTU_DISCOVER` on Windows, because recently I have been working on [this project of mine](https://github.com/database64128/swgp-go) and it requires disabling IP fragmentation. The code dealing with disabling IP fragmentation on Linux, Windows, macOS and FreeBSD is [here](https://github.com/database64128/swgp-go/tree/main/conn). I can confirm it works as intended on my Windows and Linux PC. A friend of mine confirmed that it also works on macOS.

**Comment by tobyxdd** [comment]
> @tobyxdd The link you referenced directly contradicts what you said. Just press Ctrl + F and search `IP_MTU_DISCOVER`.
> 
> If you have any Windows device around, open `"C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared\ws2ipdef.h"` and go to line 121. Everything I mentioned is right there.
> 
> I suggested using `IP_MTU_DISCOVER` on Windows, because recently I have been working on [this project of mine](https://github.com/database64128/swgp-go) and it requires disabling IP fragmentation. The code dealing with disabling IP fragmentation on Linux, Windows, macOS and FreeBSD is [here](https://github.com/database64128/swgp-go/tree/main/conn). I can confirm it works as intended on my Windows and Linux PC. A friend of mine confirmed that it also works on macOS.

My bad. I did see `IP_MTU_DISCOVER`, but since it's not listed in the "Windows support for IP_PROTO options" chart, I thought it was unsupported. I'll give it a try later today, and possibly submit a new PR.
