### PR TITLE
fix a deadlock when setting read and write deadlines

### LINKED ISSUE #1662: Race / Deadlock when using SetDeadline concurrently with Read
There appears to be a race consuming from the deadline timeout channel when calling SetReadDeadline() concurrently with an ongoing Read().  It results in a deadlock that can shut down a session.  Possibly this is a "don't-do-that" but since net.Conn generally allows this, I'm assuming it's intended to work?

The two competing channel reads are here:
https://github.com/lucas-clemente/quic-go/blob/master/receive_stream.go#L138
https://github.com/lucas-clemente/quic-go/blob/master/receive_stream.go#L268

Read does not hold a mutex when waiting on this channel, so these can race and sometimes leave SetDeadline waiting forever while holding the stream lock.

(there is an analogous block of code in the send_stream that is likely a similar problem)

Here is a test that tends to deadlock for me: 
https://gist.github.com/ltucker/849049aeaa5ca13e2496ebb66f5c6119

Here is a typical state when deadlocked:

```
goroutine 7 [running]:
testing.(*M).startAlarm.func1()
    /usr/local/go/src/testing/testing.go:1240 +0xfc
created by time.goFunc
    /usr/local/go/src/time/sleep.go:172 +0x44

goroutine 1 [chan receive]:
testing.(*T).Run(0xc4200d20f0, 0x12d20f7, 0x14, 0x12df418, 0x10733f6)
    /usr/local/go/src/testing/testing.go:825 +0x301
testing.runTests.func1(0xc4200d2000)
    /usr/local/go/src/testing/testing.go:1063 +0x64
testing.tRunner(0xc4200d2000, 0xc420055df8)
    /usr/local/go/src/testing/testing.go:777 +0xd0
testing.runTests(0xc4200a62c0, 0x1430bd0, 0x1, 0x1, 0x1011789)
    /usr/local/go/src/testing/testing.go:1061 +0x2c4
testing.(*M).Run(0xc4200d0000, 0x0)
    /usr/local/go/src/testing/testing.go:978 +0x171
main.main()
    _testmain.go:42 +0x151

goroutine 20 [semacquire]:
sync.runtime_SemacquireMutex(0xc42008e384, 0xc420051c00)
    /usr/local/go/src/runtime/sema.go:71 +0x3d
sync.(*Mutex).Lock(0xc42008e380)
    /usr/local/go/src/sync/mutex.go:134 +0x108
github.com/lucas-clemente/quic-go.(*receiveStream).readImpl(0xc42008e380, 0xc420246338, 0x6, 0x6, 0x0, 0x0, 0x0, 0x0)
    /Users/ltucker/go/src/github.com/lucas-clemente/quic-go/receive_stream.go:141 +0x27f
github.com/lucas-clemente/quic-go.(*receiveStream).Read(0xc42008e380, 0xc420246338, 0x6, 0x6, 0x0, 0x0, 0x0)
    /Users/ltucker/go/src/github.com/lucas-clemente/quic-go/receive_stream.go:79 +0x50
github.com/ltucker/qd4.TestDeadlineDeadlock(0xc4200d20f0)
    /Users/ltucker/go/src/github.com/ltucker/qd4/deadlock_test.go:57 +0x2fc
testing.tRunner(0xc4200d20f0, 0x12df418)
    /usr/local/go/src/testing/testing.go:777 +0xd0
created by testing.(*T).Run
    /usr/local/go/src/testing/testing.go:824 +0x2e0

goroutine 21 [sleep]:
time.Sleep(0x5f5e100)
    /usr/local/go/src/runtime/time.go:102 +0x166
github.com/ltucker/qd4.helloServer(0x0, 0x0)
    /Users/ltucker/go/src/github.com/ltucker/qd4/deadlock_test.go:94 +0x2e5
github.com/ltucker/qd4.TestDeadlineDeadlock.func1()
    /Users/ltucker/go/src/github.com/ltucker/qd4/deadlock_test.go:26 +0x22
created by github.com/ltucker/qd4.TestDeadlineDeadlock
    /Users/ltucker/go/src/github.com/ltucker/qd4/deadlock_test.go:25 +0x47

goroutine 22 [IO wait]:
internal/poll.runtime_pollWait(0x20c0ea0, 0x72, 0x0)
    /usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc4200d0098, 0x72, 0x0, 0x0, 0x0)
    /usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc4200d0098, 0xc42032a000, 0x5ac, 0x5ac)
    /usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).ReadFrom(0xc4200d0080, 0xc42032a000, 0x5ac, 0x5ac, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/internal/poll/fd_unix.go:207 +0x17d
net.(*netFD).readFrom(0xc4200d0080, 0xc42032a000, 0x5ac, 0x5ac, 0xc42002d670, 0xc42002d738, 0x1220adf, 0xc4200da000, 0xc4200d6d20)
    /usr/local/go/src/net/fd_unix.go:208 +0x5b
net.(*UDPConn).readFrom(0xc4200a2020, 0xc42032a000, 0x5ac, 0x5ac, 0xc420060848, 0xc4200f8000, 0x0, 0xc42002d738)
    /usr/local/go/src/net/udpsock_posix.go:47 +0x6a
net.(*UDPConn).ReadFrom(0xc4200a2020, 0xc42032a000, 0x5ac, 0x5ac, 0x1d, 0x5ac, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/udpsock.go:118 +0x6f
github.com/lucas-clemente/quic-go.(*packetHandlerMap).listen(0xc4200da000)
    /Users/ltucker/go/src/github.com/lucas-clemente/quic-go/packet_handler_map.go:151 +0x83
created by github.com/lucas-clemente/quic-go.newPacketHandlerMap
    /Users/ltucker/go/src/github.com/lucas-clemente/quic-go/packet_handler_map.go:52 +0xf7

goroutine 37 [semacquire]:
sync.runtime_SemacquireMutex(0xc42008e384, 0xc420276000)
    /usr/local/go/src/runtime/sema.go:71 +0x3d
sync.(*Mutex).Lock(0xc42008e380)
    /usr/local/go/src/sync/mutex.go:134 +0x108
github.com/lucas-clemente/quic-go.(*receiveStream).handleStreamFrame(0xc42008e380, 0xc42024ab70, 0x0, 0x0)
    /Users/ltucker/go/src/github.com/lucas-clemente/quic-go/receive_stream.go:208 +0x82
github.com/lucas-clemente/quic-go.(*session).handleStreamFrame(0xc420270000, 0xc42024ab70, 0x3, 0xc42024ab70, 0xc420253a00)
    /Users/ltucker/go/src/github.com/lucas-clemente/quic-go/session.go:666 +0x174
github.com/lucas-clemente/quic-go.(*session).handleFrames(0xc420270000, 0xc420244b20, 0x1, 0x2, 0x7, 0x3, 0x0, 0x0)
    /Users/ltucker/go/src/github.com/lucas-clemente/quic-go/session.go:571 +0x4a3
github.com/lucas-clemente/quic-go.(*session).handlePacketImpl(0xc420270000, 0xc42026c410, 0x0, 0x0)
    /Users/ltucker/go/src/github.com/lucas-clemente/quic-go/session.go:560 +0x679
github.com/lucas-clemente/quic-go.(*session).run(0xc420270000, 0x0, 0x0)
    /Users/ltucker/go/src/github.com/lucas-clemente/quic-go/session.go:364 +0xb1c
github.com/lucas-clemente/quic-go.(*client).establishSecureConnection.func1(0xc4200d21e0, 0xc420116960)
    /Users/ltucker/go/src/github.com/lucas-clemente/quic-go/client.go:274 +0x41
created by github.com/lucas-clemente/quic-go.(*client).establishSecureConnection
    /Users/ltucker/go/src/github.com/lucas-clemente/quic-go/client.go:273 +0x7f

goroutine 4 [IO wait]:
internal/poll.runtime_pollWait(0x20c0dd0, 0x72, 0x0)
    /usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc420236018, 0x72, 0x0, 0x0, 0x0)
    /usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc420236018, 0xc42023b800, 0x5ac, 0x5ac)
    /usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).ReadFrom(0xc420236000, 0xc42023b800, 0x5ac, 0x5ac, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/internal/poll/fd_unix.go:207 +0x17d
net.(*netFD).readFrom(0xc420236000, 0xc42023b800, 0x5ac, 0x5ac, 0xc42002de70, 0xc42002df38, 0x1220adf, 0xc4202260e0, 0xc4200a4960)
    /usr/local/go/src/net/fd_unix.go:208 +0x5b
net.(*UDPConn).readFrom(0xc42000e020, 0xc42023b800, 0x5ac, 0x5ac, 0xc420098b08, 0xc4200f8100, 0x0, 0xc42002df38)
    /usr/local/go/src/net/udpsock_posix.go:47 +0x6a
net.(*UDPConn).ReadFrom(0xc42000e020, 0xc42023b800, 0x5ac, 0x5ac, 0x1b, 0x5ac, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/udpsock.go:118 +0x6f
github.com/lucas-clemente/quic-go.(*packetHandlerMap).listen(0xc4202260e0)
    /Users/ltucker/go/src/github.com/lucas-clemente/quic-go/packet_handler_map.go:151 +0x83
created by github.com/lucas-clemente/quic-go.newPacketHandlerMap
    /Users/ltucker/go/src/github.com/lucas-clemente/quic-go/packet_handler_map.go:52 +0xf7

goroutine 51 [select]:
github.com/lucas-clemente/quic-go.(*session).run(0xc4200f8600, 0x0, 0x0)
    /Users/ltucker/go/src/github.com/lucas-clemente/quic-go/session.go:353 +0x39b
created by github.com/lucas-clemente/quic-go.(*server).createNewSession
    /Users/ltucker/go/src/github.com/lucas-clemente/quic-go/server.go:423 +0x33e

goroutine 26 [chan receive]:
github.com/lucas-clemente/quic-go.(*receiveStream).SetReadDeadline(0xc42008e380, 0xbef9e3d14a06025d, 0x188f23b8, 0x14399a0, 0x0, 0x0)
    /Users/ltucker/go/src/github.com/lucas-clemente/quic-go/receive_stream.go:268 +0x1b4
github.com/ltucker/qd4.TestDeadlineDeadlock.func2(0x20842d8, 0xc42008e380)
    /Users/ltucker/go/src/github.com/ltucker/qd4/deadlock_test.go:48 +0x62
created by github.com/ltucker/qd4.TestDeadlineDeadlock
    /Users/ltucker/go/src/github.com/ltucker/qd4/deadlock_test.go:46 +0x1d5
```

### PR DESCRIPTION
**Pull request by marten-seemann**
Fixes #1662.

@ltucker, can you please have a look?
I added some integration tests loosely based on your example, so we'll be sure that this bug won't occur again in the future. Furthermore, our integration tests are run with race detector on the CI, so we're checking that it's thread-safe as well.

### CODE REVIEW

**Comment by marten-seemann** [comment]
I fixed the race condition in the stream unit tests, and the CI should be happy now. This PR is ready for merging now.

**Comment by ltucker** [comment]
working for me

**Comment by marten-seemann** [comment]
@lucas-clemente: Could you please review this?
I'm also planning to cherry-pick the recent stream-related changes onto the `gquic` branch, once this is merged.

File: receive_stream.go [hunk 1]
```diff
@@ -121,21 +122,29 @@ func (s *receiveStream) readImpl(p []byte) (bool /*stream completed */, int, err
 				return false, bytesRead, s.resetRemotelyErr
 			}
 
-			if !s.deadline.IsZero() && !time.Now().Before(s.deadline) {
-				return false, bytesRead, errDeadline
+			deadline := s.deadline
+			if !deadline.IsZero() {
+				if !time.Now().Before(deadline) {
```
Comment (lucas-clemente) [inline receive_stream.go]: I'm guessing this is an optimization, not an actual check? Maybe you should add a comment that says so.

Comment (marten-seemann) [reply receive_stream.go]: Why do you think this is an optimization?

Comment (lucas-clemente) [reply receive_stream.go]: Well, it's either that or a race condition, no? The code has to deal with the case of the deadline being less than now one instruction after this check, so it can't rely on the check for correctness.

Comment (marten-seemann) [reply receive_stream.go]: It’s inside the mutex so there’s no race here. Also, this check is in the for loop, so this is a necessary way to exit that loop after the deadline expires, not an optimization.

Comment (lucas-clemente) [reply receive_stream.go]: Oh right, I missed the for loop 🙄LGTM
