### PR TITLE
fix window update race

### LINKED ISSUE #1055: race condition in rttStats
```
==================

WARNING: DATA RACE

Write at 0x00c42009a860 by goroutine 17:

  github.com/lucas-clemente/quic-go/congestion.(*RTTStats).UpdateRTT()

      /home/travis/gopath/src/github.com/lucas-clemente/quic-go/congestion/rtt_stats.go:114 +0x35b

  github.com/lucas-clemente/quic-go/ackhandler.(*sentPacketHandler).maybeUpdateRTT()

      /home/travis/gopath/src/github.com/lucas-clemente/quic-go/ackhandler/sent_packet_handler.go:256 +0x263

  github.com/lucas-clemente/quic-go/ackhandler.(*sentPacketHandler).ReceivedAck()

      /home/travis/gopath/src/github.com/lucas-clemente/quic-go/ackhandler/sent_packet_handler.go:175 +0x3f2

  github.com/lucas-clemente/quic-go.(*session).handleAckFrame()

      /home/travis/gopath/src/github.com/lucas-clemente/quic-go/session.go:637 +0xdc

  github.com/lucas-clemente/quic-go.(*session).handleFrames()

      /home/travis/gopath/src/github.com/lucas-clemente/quic-go/session.go:522 +0x22c

  github.com/lucas-clemente/quic-go.(*session).handlePacketImpl()

      /home/travis/gopath/src/github.com/lucas-clemente/quic-go/session.go:511 +0x803

  github.com/lucas-clemente/quic-go.(*session).run()

      /home/travis/gopath/src/github.com/lucas-clemente/quic-go/session.go:366 +0x10fb

  github.com/lucas-clemente/quic-go.(*client).establishSecureConnection.func1()

      /home/travis/gopath/src/github.com/lucas-clemente/quic-go/client.go:252 +0x63


Previous read at 0x00c42009a860 by goroutine 10:

  github.com/lucas-clemente/quic-go/internal/flowcontrol.(*baseFlowController).maybeAdjustWindowIncrement()

      /home/travis/gopath/src/github.com/lucas-clemente/quic-go/congestion/rtt_stats.go:68 +0x105

  github.com/lucas-clemente/quic-go/internal/flowcontrol.(*baseFlowController).getWindowUpdate()

      /home/travis/gopath/src/github.com/lucas-clemente/quic-go/internal/flowcontrol/base_flow_controller.go:70 +0xe1

  github.com/lucas-clemente/quic-go/internal/flowcontrol.(*streamFlowController).GetWindowUpdate()

      /home/travis/gopath/src/github.com/lucas-clemente/quic-go/internal/flowcontrol/stream_flow_controller.go:122 +0xa8

  github.com/lucas-clemente/quic-go.(*receiveStream).Read()

      /home/travis/gopath/src/github.com/lucas-clemente/quic-go/receive_stream.go:143 +0x982

  github.com/lucas-clemente/quic-go.(*stream).Read()

      <autogenerated>:1 +0x69

  bytes.(*Buffer).ReadFrom()

      /home/travis/.gimme/versions/go1.9.2.linux.amd64/src/bytes/buffer.go:209 +0x1dd

  io.copyBuffer()

      /home/travis/.gimme/versions/go1.9.2.linux.amd64/src/io/io.go:386 +0x348

  io.Copy()

      /home/travis/.gimme/versions/go1.9.2.linux.amd64/src/io/io.go:362 +0x7e

  github.com/lucas-clemente/quic-go/benchmark.init.1.func1.1.1.2()

      /home/travis/gopath/src/github.com/lucas-clemente/quic-go/benchmark/benchmark_test.go:74 +0x91

  github.com/onsi/ginkgo/internal/leafnodes.(*benchmarker).Time()

      /home/travis/gopath/src/github.com/onsi/ginkgo/internal/leafnodes/benchmarker.go:26 +0x86

  github.com/lucas-clemente/quic-go/benchmark.init.1.func1.1.1()

      /home/travis/gopath/src/github.com/lucas-clemente/quic-go/benchmark/benchmark_test.go:73 +0x6a9

  runtime.call32()

      /home/travis/.gimme/versions/go1.9.2.linux.amd64/src/runtime/asm_amd64.s:509 +0x3a

  reflect.Value.Call()

      /home/travis/.gimme/versions/go1.9.2.linux.amd64/src/reflect/value.go:302 +0xc0

  github.com/onsi/ginkgo/internal/leafnodes.NewMeasureNode.func1()

      /home/travis/gopath/src/github.com/onsi/ginkgo/internal/leafnodes/measure_node.go:23 +0x16a

  github.com/onsi/ginkgo/internal/leafnodes.(*runner).runSync()

      /home/travis/gopath/src/github.com/onsi/ginkgo/internal/leafnodes/runner.go:110 +0xbb

  github.com/onsi/ginkgo/internal/leafnodes.(*runner).run()

      /home/travis/gopath/src/github.com/onsi/ginkgo/internal/leafnodes/runner.go:64 +0x17d

  github.com/onsi/ginkgo/internal/leafnodes.(*MeasureNode).Run()

      /home/travis/gopath/src/github.com/onsi/ginkgo/internal/leafnodes/measure_node.go:37 +0xa3

  github.com/onsi/ginkgo/internal/spec.(*Spec).runSample()

      /home/travis/gopath/src/github.com/onsi/ginkgo/internal/spec/spec.go:176 +0x767

  github.com/onsi/ginkgo/internal/spec.(*Spec).Run()

      /home/travis/gopath/src/github.com/onsi/ginkgo/internal/spec/spec.go:127 +0x118

  github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpec()

      /home/travis/gopath/src/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:198 +0x17c

  github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpecs()

      /home/travis/gopath/src/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:168 +0x62d

  github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).Run()

      /home/travis/gopath/src/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:64 +0x103

  github.com/onsi/ginkgo/internal/suite.(*Suite).Run()

      /home/travis/gopath/src/github.com/onsi/ginkgo/internal/suite/suite.go:62 +0x3d0

  github.com/onsi/ginkgo.RunSpecsWithCustomReporters()

      /home/travis/gopath/src/github.com/onsi/ginkgo/ginkgo_dsl.go:218 +0x324

  github.com/onsi/ginkgo.RunSpecs()

      /home/travis/gopath/src/github.com/onsi/ginkgo/ginkgo_dsl.go:199 +0x367

  github.com/lucas-clemente/quic-go/benchmark.TestBenchmark()

      /home/travis/gopath/src/github.com/lucas-clemente/quic-go/benchmark/benchmark_suite_test.go:14 +0x88

  testing.tRunner()

      /home/travis/.gimme/versions/go1.9.2.linux.amd64/src/testing/testing.go:746 +0x16c


Goroutine 17 (running) created at:

  github.com/lucas-clemente/quic-go.(*client).establishSecureConnection()

      /home/travis/gopath/src/github.com/lucas-clemente/quic-go/client.go:251 +0xe5

  github.com/lucas-clemente/quic-go.(*client).dialGQUIC()

      /home/travis/gopath/src/github.com/lucas-clemente/quic-go/client.go:202 +0x86

  github.com/lucas-clemente/quic-go.(*client).dial()

      /home/travis/gopath/src/github.com/lucas-clemente/quic-go/client.go:190 +0x140

  github.com/lucas-clemente/quic-go.DialNonFWSecure()

      /home/travis/gopath/src/github.com/lucas-clemente/quic-go/client.go:120 +0x76c

  github.com/lucas-clemente/quic-go.Dial()

      /home/travis/gopath/src/github.com/lucas-clemente/quic-go/client.go:135 +0xab

  github.com/lucas-clemente/quic-go.DialAddr()

      /home/travis/gopath/src/github.com/lucas-clemente/quic-go/client.go:60 +0x24c

  github.com/lucas-clemente/quic-go/benchmark.init.1.func1.1.1()

      /home/travis/gopath/src/github.com/lucas-clemente/quic-go/benchmark/benchmark_test.go:60 +0x382

  runtime.call32()

      /home/travis/.gimme/versions/go1.9.2.linux.amd64/src/runtime/asm_amd64.s:509 +0x3a

  reflect.Value.Call()

      /home/travis/.gimme/versions/go1.9.2.linux.amd64/src/reflect/value.go:302 +0xc0

  github.com/onsi/ginkgo/internal/leafnodes.NewMeasureNode.func1()

      /home/travis/gopath/src/github.com/onsi/ginkgo/internal/leafnodes/measure_node.go:23 +0x16a

  github.com/onsi/ginkgo/internal/leafnodes.(*runner).runSync()

      /home/travis/gopath/src/github.com/onsi/ginkgo/internal/leafnodes/runner.go:110 +0xbb

  github.com/onsi/ginkgo/internal/leafnodes.(*runner).run()

      /home/travis/gopath/src/github.com/onsi/ginkgo/internal/leafnodes/runner.go:64 +0x17d

  github.com/onsi/ginkgo/internal/leafnodes.(*MeasureNode).Run()

      /home/travis/gopath/src/github.com/onsi/ginkgo/internal/leafnodes/measure_node.go:37 +0xa3

  github.com/onsi/ginkgo/internal/spec.(*Spec).runSample()

      /home/travis/gopath/src/github.com/onsi/ginkgo/internal/spec/spec.go:176 +0x767

  github.com/onsi/ginkgo/internal/spec.(*Spec).Run()

      /home/travis/gopath/src/github.com/onsi/ginkgo/internal/spec/spec.go:127 +0x118

  github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpec()

      /home/travis/gopath/src/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:198 +0x17c

  github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpecs()

      /home/travis/gopath/src/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:168 +0x62d

  github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).Run()

      /home/travis/gopath/src/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:64 +0x103

  github.com/onsi/ginkgo/internal/suite.(*Suite).Run()

      /home/travis/gopath/src/github.com/onsi/ginkgo/internal/suite/suite.go:62 +0x3d0

  github.com/onsi/ginkgo.RunSpecsWithCustomReporters()

      /home/travis/gopath/src/github.com/onsi/ginkgo/ginkgo_dsl.go:218 +0x324

  github.com/onsi/ginkgo.RunSpecs()

      /home/travis/gopath/src/github.com/onsi/ginkgo/ginkgo_dsl.go:199 +0x367

  github.com/lucas-clemente/quic-go/benchmark.TestBenchmark()

      /home/travis/gopath/src/github.com/lucas-clemente/quic-go/benchmark/benchmark_suite_test.go:14 +0x88

  testing.tRunner()

      /home/travis/.gimme/versions/go1.9.2.linux.amd64/src/testing/testing.go:746 +0x16c


Goroutine 10 (running) created at:

  testing.(*T).Run()

      /home/travis/.gimme/versions/go1.9.2.linux.amd64/src/testing/testing.go:789 +0x568

  testing.runTests.func1()

      /home/travis/.gimme/versions/go1.9.2.linux.amd64/src/testing/testing.go:1004 +0xa7

  testing.tRunner()

      /home/travis/.gimme/versions/go1.9.2.linux.amd64/src/testing/testing.go:746 +0x16c

  testing.runTests()

      /home/travis/.gimme/versions/go1.9.2.linux.amd64/src/testing/testing.go:1002 +0x521

  testing.(*M).Run()

      /home/travis/.gimme/versions/go1.9.2.linux.amd64/src/testing/testing.go:921 +0x206

  main.main()

      github.com/lucas-clemente/quic-go/benchmark/_test/_testmain.go:44 +0x1d3

==================
```

### PR DESCRIPTION
**Pull request by marten-seemann**
Fixes #1055.

### CODE REVIEW

File: session_test.go [hunk 1]
```diff
@@ -878,23 +878,23 @@ var _ = Describe("Session", func() {
...
+		// 	sph.EXPECT().DequeuePacketForRetransmission()
+		// 	sph.EXPECT().ShouldSendRetransmittablePacket()
+		// 	sph.EXPECT().SentPacket(gomock.Any()).Do(func(p *ackhandler.Packet) {
+		// 		Expect(p.Frames).To(ContainElement(&wire.MaxStreamDataFrame{StreamID: 1, ByteOffset: 10}))
+		// 		Expect(p.Frames).To(ContainElement(&wire.MaxStreamDataFrame{StreamID: 2, ByteOffset: 20}))
+		// 	})
+		// 	sess.sentPacketHandler = sph
+		// 	err := sess.sendPacket()
+		// 	Expect(err).ToNot(HaveOccurred())
+		// })
```
Comment (lucas-clemente) [inline session_test.go]: No commented code!11!

Comment (marten-seemann) [reply session_test.go]: There should be a way to automate this.
