### PR TITLE
fix a crash in the http3.Server when GetConfigForClient returns nil

### LINKED ISSUE #2924: panic when GetConfigForClient returns nil
[crypto/tls Document](https://pkg.go.dev/crypto/tls#Config) says: If the returned Config is nil, the original Config will be used.

```go
http3.Server{
	Server: &http.Server{
		Addr:      ":https",
		Handler:   nil,
		TLSConfig: &tls.Config{
			GetConfigForClient: tlsConfigOverride,
		},
	},
	QuicConfig: &quic.Config{
		KeepAlive: true,
	},
}

func tlsConfigOverride(hello *tls.ClientHelloInfo) (*tls.Config, error) {
	if (...) {
		return config, nil
	}

	return nil, nil
}
```

But I got:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x148 pc=0x61a141]

goroutine 63 [running]:
crypto/tls.(*Config).Clone(0x0, 0x0)
        /usr/lib/go/src/crypto/tls/common.go:733 +0x41
github.com/lucas-clemente/quic-go/http3.(*Server).serveImpl.func2(0xc00027e3c0, 0xc0000b2240, 0xc00027e3c0, 0x0)
        /home/liming/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.19.2/http3/server.go:152 +0x93
github.com/marten-seemann/qtls-go1-15.(*Conn).readClientHello(0xc000241c00, 0x44a457, 0xc00052e8e8, 0x0)
        /home/liming/go/pkg/mod/github.com/marten-seemann/qtls-go1-15@v0.1.1/handshake_server.go:149 +0x4b1
github.com/marten-seemann/qtls-go1-15.(*Conn).serverHandshake(0xc000241c00, 0x0, 0xc00052e8a0)
        /home/liming/go/pkg/mod/github.com/marten-seemann/qtls-go1-15@v0.1.1/handshake_server.go:42 +0x56
github.com/marten-seemann/qtls-go1-15.(*Conn).Handshake(0xc000241c00, 0x0, 0x0)
        /home/liming/go/pkg/mod/github.com/marten-seemann/qtls-go1-15@v0.1.1/conn.go:1417 +0xc9
github.com/lucas-clemente/quic-go/internal/handshake.(*cryptoSetup).RunHandshake.func1(0xc000263c80, 0xc000303da0, 0xc00052e900)
        /home/liming/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.19.2/internal/handshake/crypto_setup.go:297 +0x5a
created by github.com/lucas-clemente/quic-go/internal/handshake.(*cryptoSetup).RunHandshake
        /home/liming/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.19.2/internal/handshake/crypto_setup.go:295 +0xa9
```

https://github.com/lucas-clemente/quic-go/blob/a76879c30599a5fe025efc5c60a9a45c9edb041c/http3/server.go#L136-L156

### PR DESCRIPTION
**Pull request by marten-seemann**
Fixes #2924.

### CODE REVIEW

File: http3/server.go [hunk 1]
```diff
@@ -149,6 +149,9 @@ func (s *Server) serveImpl(tlsConf *tls.Config, conn net.PacketConn) error {
 					return nil, err
 				}
 			}
+			if conf == nil {
+				return nil, nil
+			}
```
Comment (jinliming2) [inline http3/server.go:154]: NextProtos may not be set if return immediately?

Comment (marten-seemann) [reply http3/server.go:157]: Good catch. Should be fixed now.

**Review by mvdan — APPROVED** [review]
